<a href="https://colab.research.google.com/github/Amankumarpandey3/Deep-Learning/blob/main/Integer_Encoding_Simple_RNN%26_Embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
docs=['go india',
      'India India',
      'Jetege bhai jeetege india Jeetege',
      'bharat mata ki jai',
      'kohli kohli',
      'Dhoni Dhoni',
      'Om Namah Shivaya'
      ]

In [5]:
# Install tensorflow if not already present (uncomment the line below if needed)
# !pip install tensorflow
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer=Tokenizer(oov_token='<nothing>')

In [6]:
tokenizer.fit_on_texts(docs)

In [7]:
tokenizer.word_index

{'<nothing>': 1,
 'india': 2,
 'jeetege': 3,
 'kohli': 4,
 'dhoni': 5,
 'go': 6,
 'jetege': 7,
 'bhai': 8,
 'bharat': 9,
 'mata': 10,
 'ki': 11,
 'jai': 12,
 'om': 13,
 'namah': 14,
 'shivaya': 15}

In [9]:
tokenizer.word_counts

OrderedDict([('go', 1),
             ('india', 4),
             ('jetege', 1),
             ('bhai', 1),
             ('jeetege', 2),
             ('bharat', 1),
             ('mata', 1),
             ('ki', 1),
             ('jai', 1),
             ('kohli', 2),
             ('dhoni', 2),
             ('om', 1),
             ('namah', 1),
             ('shivaya', 1)])

In [11]:
tokenizer.document_count

7

In [12]:
sequences=tokenizer.texts_to_sequences(docs)

In [13]:
sequences

[[6, 2],
 [2, 2],
 [7, 8, 3, 2, 3],
 [9, 10, 11, 12],
 [4, 4],
 [5, 5],
 [13, 14, 15]]

In [15]:
from keras.utils import pad_sequences


In [17]:
sequences=pad_sequences(sequences,padding='post')

In [18]:
sequences

array([[ 6,  2,  0,  0,  0],
       [ 2,  2,  0,  0,  0],
       [ 7,  8,  3,  2,  3],
       [ 9, 10, 11, 12,  0],
       [ 4,  4,  0,  0,  0],
       [ 5,  5,  0,  0,  0],
       [13, 14, 15,  0,  0]], dtype=int32)

In [19]:
from keras.datasets import imdb
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [20]:
(X_train,y_train),(X_test,y_test)=imdb.load_data()

17464789/17464789 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [21]:
X_train


array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 22665, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 21631, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 19193, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 10311, 8, 4, 107, 117, 5952, 15, 256, 4, 31050, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 12118, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
       list([1, 194, 1

In [22]:
X_train=pad_sequences(X_train,padding='post',maxlen=50)
X_test=pad_sequences(X_test,padding='post',maxlen=50)

In [23]:
X_train.shape

(25000, 50)

In [24]:
model=Sequential()
model.add(SimpleRNN(32,input_shape=(50,1),return_sequences=False))
model.add(Dense(1,activation='sigmoid'))
model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn (SimpleRNN)          │ (None, 32)             │         1,088 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,121 (4.38 KB)

 Trainable params: 1,121 (4.38 KB)

 Non-trainable params: 0 (0.00 B)

In [25]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model.fit(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 15s 14ms/step - accuracy: 0.5070 - loss: 0.6970 - val_accuracy: 0.5039 - val_loss: 0.6958
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 11s 14ms/step - accuracy: 0.5081 - loss: 0.6932 - val_accuracy: 0.5015 - val_loss: 0.6942
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 11s 14ms/step - accuracy: 0.5053 - loss: 0.6930 - val_accuracy: 0.5006 - val_loss: 0.6969
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 11s 14ms/step - accuracy: 0.5114 - loss: 0.6929 - val_accuracy: 0.5033 - val_loss: 0.6939
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 10s 13ms/step - accuracy: 0.5096 - loss: 0.6923 - val_accuracy: 0.5022 - val_loss: 0.6943


In [27]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer=Tokenizer()

In [28]:
tokenizer.fit_on_texts(docs)

In [30]:
from keras.utils import pad_sequences
sequences=tokenizer.texts_to_sequences(docs)
sequences

[[5, 1], [1, 1], [6, 7, 2, 1, 2], [8, 9, 10, 11], [3, 3], [4, 4], [12, 13, 14]]

In [31]:
model=Sequential()
model.add(Embedding(17,output_dim=2,input_length=5))
model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [32]:
model.compile('adam','accuracy')

In [37]:
import numpy as np

pred=model.predict(np.array(sequences_padded))
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 192ms/step
[[[-0.02367679 -0.0466417 ]
  [-0.03925407 -0.0057071 ]
  [-0.01566545 -0.0452234 ]
  [-0.01566545 -0.0452234 ]
  [-0.01566545 -0.0452234 ]]

 [[-0.03925407 -0.0057071 ]
  [-0.03925407 -0.0057071 ]
  [-0.01566545 -0.0452234 ]
  [-0.01566545 -0.0452234 ]
  [-0.01566545 -0.0452234 ]]

 [[-0.04153161  0.0474096 ]
  [-0.02317661  0.04716105]
  [ 0.00678456 -0.04052781]
  [-0.03925407 -0.0057071 ]
  [ 0.00678456 -0.04052781]]

 [[ 0.00516618  0.01338487]
  [-0.03231972  0.01359059]
  [ 0.03738183 -0.04949716]
  [-0.04609188  0.01746329]
  [-0.01566545 -0.0452234 ]]

 [[ 0.04202456  0.01028287]
  [ 0.04202456  0.01028287]
  [-0.01566545 -0.0452234 ]
  [-0.01566545 -0.0452234 ]
  [-0.01566545 -0.0452234 ]]

 [[ 0.01080937 -0.01919987]
  [ 0.01080937 -0.01919987]
  [-0.01566545 -0.0452234 ]
  [-0.01566545 -0.0452234 ]
  [-0.01566545 -0.0452234 ]]

 [[ 0.04043806 -0.03794967]
  [-0.03060615 -0.03452827]
  [ 0.01739055 -0.00905949]
  [-0.01566545 -0.0452234

In [35]:
from keras.utils import pad_sequences

sequences_padded = pad_sequences(sequences, padding='post')

In [39]:
from keras.layers import Input
model=Sequential()
model.add(Input(shape=(50,)))
model.add(Embedding(10000,2))
model.add(SimpleRNN(32,return_sequences=False))
model.add(Dense(1,activation='sigmoid'))
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 50, 2)          │        20,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_1 (SimpleRNN)        │ (None, 32)             │         1,120 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 21,153 (82.63 KB)

 Trainable params: 21,153 (82.63 KB)

 Non-trainable params: 0 (0.00 B)